language: node_js
node_js:
  - "8.11.2"
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  # NOTE: Configures dotenv for tests. See comment in `configureTestEnv.js`
  - cp .env.example .env
script:
  - yarn run lint
cache:
  yarn: true
  directories:
    - node_modules
