swagger: "2.0"
info:
  version: "1.0.0"
  title: Fitbaw!
host: localhost:10010
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /health:
    x-swagger-router-controller: healthRoute
    get:
      description: Healthcheck endpoint
      operationId: getHealth
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    x-swagger-router-controller: helloRoute
    get:
      description: Returns a cheery hello
      operationId: getHello
      parameters:
        - name: name
          in: query
          description: name
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
      x-swagger-router-controller: loginRoute
      post:
        description: login
        operationId: login
        parameters:
          - name: login
            in: body
            description: login
            required: true
            schema:
              $ref: "#/definitions/LoginBody"
        responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/HelloResponse"
          # responses may fall through to errors
          "403":
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
definitions:
  MessageResponse:
    required:
      - message
    properties:
      message:
        type: string
  HelloResponse:
    required:
      - name
    properties:
      name:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  LoginBody:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string


